"""create_initial_tables

Revision ID: 24661e7e4c0d
Revises: 9e8a1f08c9f6
Create Date: 2026-06-02 14:21:27.690309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24661e7e4c0d'
down_revision: Union[str, Sequence[str], None] = '9e8a1f08c9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
